### ISSUE TITLE
enable github pages

### ISSUE THREAD

**Issue by adabadadudu** [Amohammadi2/Svelte-Notification-System-Tutorial#1]
go to setting->pages and enable github pages.

in github pages who want to see output can see result

**Comment by Amohammadi2** [comment]
Hi. Thanks for your remark on github pages. I'll perform the requested action as soon as I find some free time.

**Comment by Amohammadi2** [comment]
Hi. An interactive demo is now available at https://amohammadi2.github.io/Svelte-Notification-System-Tutorial/

the issue is going to be closed.
